describe('Compras na ProductStore', () => {
    it('Login', ()=>{
        cy.visit('https://www.demoblaze.com/index.html')
        cy.get('#login2').click()
        cy.wait(1000)
        cy.get('#loginusername')
            .type('hg_kaua')
            .should('have.value', 'hg_kaua')
        cy.get('#loginpassword').type('s3cret')
        cy.get('button').contains('Log in').click()
        
    })
    it('Fluxo de compras celulares', ()=>{
        // compra do sansung galaxy s7
        cy.get('#nameofuser').contains('Welcome hg_kaua').should('be.visible')
        cy.get('#itemc').contains('Phones').click()
        cy.get('.card-title').contains('Samsung galaxy s7').click()
        cy.get('.price-container').contains('$800').should('be.visible')
        cy.get('#tbodyid > div.row > div > a').should('be.visible').click()
        cy.get('#navbarExample > ul > li.nav-item.active > a').click()
        // compra do iphone 6 32gb
        cy.url().should('include', 'https://www.demoblaze.com/index.html')
        cy.get('#itemc').contains('Phones').click()
        cy.get('.card-title').contains('Iphone 6 32gb').click()
        cy.get('.price-container').contains('$790').should('be.visible')
        cy.get('#tbodyid > div.row > div > a').should('be.visible').click()
        cy.get('#navbarExample > ul > li.nav-item.active > a').click()
        // compra do nexus 6
        cy.url().should('include', 'https://www.demoblaze.com/index.html')
        cy.get('#itemc').contains('Phones').click()
        cy.get('.card-title').contains('Nexus 6').click()
        cy.get('.price-container').contains('$650').should('be.visible')
        cy.get('#tbodyid > div.row > div > a').should('be.visible').click()
        cy.get('#navbarExample > ul > li.nav-item.active > a').click()
        // compra do macbook pro
        cy.url().should('include', 'https://www.demoblaze.com/index.html')
        cy.get('.list-group-item').contains('Laptops').click()
        cy.get('.card-title').contains('MacBook Pro').click()
        cy.get('.price-container').contains('$1100').should('be.visible')
        cy.get('#tbodyid > div.row > div > a').should('be.visible').click()
        cy.get('#navbarExample > ul > li.nav-item.active > a').click()
    })
    it('Cancelamento Nexus 6', ()=>{
        cy.url().should('include', 'https://www.demoblaze.com/index.html')
        cy.get('#cartur').click()
        cy.get('#totalp').should('have.text', '3340')
        cy.get('.success').contains('Nexus 6')
            .parent()
            .find('td:nth-child(4) > a')
            .click()
        cy.get('#totalp').should('have.text', '2690')
        cy.get('.btn.btn-success').click()
    })
    it('Finalização de compra', ()=>{
        cy.get('#name').should('be.empty').type('hg_kaua')
        cy.get('#country').should('be.empty').type('Brasil')
        cy.get('#city').should('be.empty').type('Rio')
        cy.get('#card').should('be.empty').type('1223 3344 4441')
        cy.get('#month').should('be.empty').type('Novembro')
        cy.get('#year').should('be.empty').type('2013')

        cy.intercept('https://api.demoblaze.com/deletecart').as('req')
        cy.get('button').contains('Purchase').click()
        cy.wait('@req').its('response.statusCode').should('eq', 200)

        cy.get('h2').contains('Thank you for your purchase!')
            .should('have.text', 'Thank you for your purchase!')
        cy.wait(1000)
        cy.get('button[class="confirm btn btn-lg btn-primary"]').contains('OK').click()
        cy.wait(1000)
        cy.url().should('include', 'https://www.demoblaze.com/index.html')
    })
})
//3340
